### ISSUE TITLE
足し算がおかしい

### ISSUE THREAD

**Issue by Taiki-Kobasako** [Matcha77/git-training-2023-06-16#2]
## 操作手順
* 足し算したら
* 値がおかしかった

## 本来の想定
* 足し算したら
* 正しい値になって欲しい

## 操作環境
* OS:Mac OS Ventura
* OSバージョン : 13.4（22F66）
* ブラウザ : Chrome
* ブラウザバージョン : バージョン: 114.0.5735.106（Official Build） （x86_64）

**Comment by hiroyohiroyo** [comment]
おつ
