### ISSUE TITLE
引き算の第一引数

### ISSUE THREAD

**Issue by Taiki-Kobasako** [Matcha77/git-training-2023-06-16#5]
## 操作手順
* 引き算 -1 - (-10) 
* おかしくなった 11

## 本来の想定
* 引き算において
* 第一引数の符号を正しく計算してほしい

## 操作環境
* OS:Mac OS Ventura
* OSバージョン : 13.4（22F66）
* ブラウザ : Chrome
* ブラウザバージョン : バージョン: 114.0.5735.106（Official Build） （x86_64）

**Comment by hiroyohiroyo** [comment]
やった！
